<script setup>
import { onMounted, ref } from 'vue'
import { Crown, Megaphone, Sparkles, Star, Store, TrendingUp, Users } from '@lucide/vue'
import { api } from '../../services/api'
import { number, money } from '../../utils'
import EntityAvatar from '../../components/EntityAvatar.vue'
import LoadingBlock from '../../components/LoadingBlock.vue'
import EmptyState from '../../components/EmptyState.vue'

const loading=ref(true),payload=ref({clubs:[],players:[]}),tab=ref('clubs')
onMounted(async()=>{try{payload.value=(await api.get('/public/influence/leaderboards',null,{auth:false})).data}catch{}finally{loading.value=false}})
</script>
<template><div><section class="influence-public-hero"><div class="container hero-inner"><div><span class="eyebrow"><Sparkles :size="15"/> Influence Index</span><h1>Sức ảnh hưởng<br/><span>của bóng đá</span></h1><p>Danh tiếng không chỉ đến từ danh hiệu. Người hâm mộ, truyền thông, ngôi sao, sân vận động và sức mạnh thương mại cùng tạo nên giá trị của một CLB.</p></div><div class="influence-globe"><i></i><i></i><i></i><div><Crown :size="46"/><b>GLOBAL<br/>INFLUENCE</b></div></div></div></section><div class="container influence-body"><LoadingBlock v-if="loading"/><template v-else><div class="public-tabs"><button :class="{active:tab==='clubs'}" @click="tab='clubs'"><Users :size="17"/>CLB ảnh hưởng nhất</button><button :class="{active:tab==='players'}" @click="tab='players'"><Star :size="17"/>Cầu thủ nổi tiếng nhất</button></div><section v-if="tab==='clubs'"><EmptyState v-if="!payload.clubs.length"/><div v-else class="influence-grid"><RouterLink v-for="club in payload.clubs" :key="club.club_id" :to="`/clubs/${club.club_id}`" class="glass influence-card"><span class="rank">#{{ club.influence_rank }}</span><EntityAvatar :src="club.logo_url" :name="club.club_name" :size="62"/><h2>{{ club.club_name }}</h2><small>{{ club.code }}</small><div class="score">{{ number(club.reputation_score,1) }}</div><div class="metrics"><span><Users :size="14"/>{{ number(club.fan_count,0) }} fan</span><span><Megaphone :size="14"/>{{ number(club.media_score,1) }}</span><span><Store :size="14"/>{{ number(club.commercial_score,1) }}</span><span><TrendingUp :size="14"/>{{ number(club.momentum_score,1) }}</span></div></RouterLink></div></section><section v-else><EmptyState v-if="!payload.players.length"/><div v-else class="influence-grid player-grid"><RouterLink v-for="player in payload.players" :key="player.player_id" :to="`/players/${player.player_id}`" class="glass influence-card"><span class="rank">#{{ player.influence_rank }}</span><EntityAvatar :src="player.photo_url" :name="player.full_name" :size="62" round/><h2>{{ player.full_name }}</h2><small>{{ player.club_name||'Cầu thủ tự do' }} · {{ player.position }}</small><div class="score">{{ number(player.popularity_score,1) }}</div><div class="metrics"><span><Star :size="14"/>Quảng cáo {{ number(player.endorsement_score,1) }}</span><span><Users :size="14"/>{{ number(player.social_followers,0) }}</span><span><Store :size="14"/>×{{ number(player.signed_merch_multiplier,2) }}</span><span>{{ money(player.market_value,true) }}</span></div></RouterLink></div></section></template></div></div></template>
<style scoped>
.influence-public-hero{position:relative;overflow:hidden;padding:76px 0;background:radial-gradient(circle at 20% 20%,rgba(57,130,255,.18),transparent 38%),radial-gradient(circle at 80% 60%,rgba(149,83,255,.12),transparent 38%)}.hero-inner{display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:60px}.hero-inner h1{font-size:clamp(52px,7vw,88px);line-height:.95;margin:18px 0}.hero-inner h1 span{background:linear-gradient(90deg,var(--primary),var(--cyan),var(--yellow));-webkit-background-clip:text;color:transparent}.hero-inner p{max-width:680px;font-size:16px}.influence-globe{height:360px;position:relative;display:grid;place-items:center}.influence-globe>i{position:absolute;border:1px solid rgba(80,150,255,.22);border-radius:50%}.influence-globe>i:nth-child(1){width:300px;height:300px}.influence-globe>i:nth-child(2){width:220px;height:220px;transform:rotateX(65deg)}.influence-globe>i:nth-child(3){width:300px;height:120px;transform:rotate(35deg)}.influence-globe>div{width:135px;height:135px;border-radius:50%;display:grid;place-content:center;text-align:center;color:var(--yellow);background:rgba(9,18,34,.9);box-shadow:0 0 80px rgba(57,130,255,.22)}.influence-globe b{font-size:11px;letter-spacing:.12em;margin-top:8px}.influence-body{padding:42px 0 80px}.public-tabs{display:flex;justify-content:center;gap:8px;margin-bottom:24px}.public-tabs button{border:1px solid var(--line);background:var(--panel);color:var(--muted);padding:11px 16px;border-radius:12px;display:flex;align-items:center;gap:7px;font-weight:750}.public-tabs button.active{background:var(--primary);color:white}.influence-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.influence-card{position:relative;padding:20px;text-align:center;transition:transform .2s,border-color .2s}.influence-card:hover{transform:translateY(-4px);border-color:rgba(80,150,255,.4)}.rank{position:absolute;left:13px;top:12px;color:var(--yellow);font-weight:900}.influence-card h2{font-size:16px;margin:12px 0 3px}.influence-card small{font-size:10px;color:var(--muted)}.score{font-size:31px;font-weight:900;margin:15px 0;color:var(--cyan)}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:6px}.metrics span{display:flex;align-items:center;justify-content:center;gap:4px;padding:7px;border-radius:8px;background:rgba(57,130,255,.055);font-size:9px;color:var(--muted)}@media(max-width:1050px){.influence-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.hero-inner{grid-template-columns:1fr}.influence-globe{height:270px}.influence-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.influence-grid{grid-template-columns:1fr}.public-tabs{flex-direction:column}}
</style>
