<script setup>
import { onMounted, ref, watch } from 'vue';import { Search, ScrollText } from '@lucide/vue'
import { api } from '../../services/api';import { uiStore } from '../../stores/ui';import { date } from '../../utils'
import PageHeader from '../../components/PageHeader.vue';import LoadingBlock from '../../components/LoadingBlock.vue';import EmptyState from '../../components/EmptyState.vue';import PaginationBar from '../../components/PaginationBar.vue'
const rows=ref([]),loading=ref(true),meta=ref({page:1,limit:30,total:0}),filters=ref({entity_table:'',action:''});let debounce
async function load(page=1){try{const r=await api.get('/audit-logs',{page,limit:30,...filters.value});rows.value=r.data;meta.value=r.meta}catch(e){uiStore.notify(e.message,'error')}finally{loading.value=false}}
watch(filters,()=>{clearTimeout(debounce);debounce=setTimeout(()=>load(1),300)},{deep:true});onMounted(()=>load())
</script>
<template><div><PageHeader eyebrow="Audit Trail" title="Nhật ký hệ thống" description="Theo dõi tài khoản nào đã thực hiện thao tác gì trên CLB, cầu thủ, ví và giải đấu."/><div class="glass card toolbar"><div class="search"><Search :size="17"/><input v-model="filters.action" class="input" placeholder="Mã hành động..."/></div><input v-model="filters.entity_table" class="input entity-filter" placeholder="Bảng dữ liệu..."/><span class="muted">{{ meta.total }} sự kiện</span></div><LoadingBlock v-if="loading"/><EmptyState v-else-if="!rows.length"/><div v-else class="glass card table-card"><div class="table-wrap"><table><thead><tr><th>Thời gian</th><th>Tài khoản</th><th>Hành động</th><th>Đối tượng</th><th>ID</th><th>Chi tiết</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{ date(r.created_at,true) }}</td><td>{{ r.username||'Hệ thống' }}</td><td><span class="badge blue">{{ r.action_code }}</span></td><td>{{ r.entity_table||'—' }}</td><td>{{ r.entity_id||'—' }}</td><td><code>{{ r.details||'—' }}</code></td></tr></tbody></table></div><PaginationBar v-bind="meta" @change="load"/></div></div></template>
<style scoped>.toolbar{display:flex;align-items:center;gap:12px;margin-bottom:18px;padding:13px}.search{display:flex;align-items:center;gap:8px;flex:1}.search .input{border:0;background:transparent;box-shadow:none}.entity-filter{max-width:220px}.table-card{padding:0;overflow:hidden}code{font-size:10px;color:var(--muted);white-space:pre-wrap}@media(max-width:650px){.toolbar{align-items:stretch;flex-direction:column}.entity-filter{max-width:none}}</style>
