<script setup>
import { ref } from 'vue';import { KeyRound, UserCircle2 } from '@lucide/vue'
import { api } from '../../services/api';import { authStore } from '../../stores/auth';import { uiStore } from '../../stores/ui'
import PageHeader from '../../components/PageHeader.vue';import EntityAvatar from '../../components/EntityAvatar.vue'
const busy=ref(false),form=ref({current_password:'',new_password:'',confirm:''})
async function change(){if(form.value.new_password!==form.value.confirm){uiStore.notify('Mật khẩu xác nhận không khớp.','error');return}busy.value=true;try{await api.put('/auth/password',{current_password:form.value.current_password,new_password:form.value.new_password});uiStore.notify('Đã đổi mật khẩu.');form.value={current_password:'',new_password:'',confirm:''}}catch(e){uiStore.notify(e.message,'error')}finally{busy.value=false}}
</script>
<template><div><PageHeader eyebrow="Account Security" title="Tài khoản" description="Quản lý thông tin đăng nhập và bảo mật tài khoản FIFA Admin hoặc tài khoản chung của CLB."/><div class="profile-grid"><section class="glass card profile-card"><EntityAvatar :src="authStore.user.value?.logoUrl" :name="authStore.user.value?.clubName||authStore.user.value?.username" :size="90" round/><div><span class="eyebrow">{{ authStore.user.value?.accountType }}</span><h2>{{ authStore.user.value?.clubName||'FIFA Admin' }}</h2><p>@{{ authStore.user.value?.username }}</p></div></section><section class="glass card"><div class="section-title"><div><span class="eyebrow"><KeyRound :size="14"/> Security</span><h2>Đổi mật khẩu</h2></div></div><form class="form-grid" @submit.prevent="change"><label class="form-group full"><span class="label">Mật khẩu hiện tại</span><input v-model="form.current_password" type="password" class="input" required/></label><label><span class="label">Mật khẩu mới</span><input v-model="form.new_password" type="password" minlength="8" class="input" required/></label><label><span class="label">Nhập lại mật khẩu</span><input v-model="form.confirm" type="password" minlength="8" class="input" required/></label><div class="form-group full actions"><button class="btn btn-primary" :disabled="busy">{{ busy?'Đang đổi...':'Đổi mật khẩu' }}</button></div></form></section></div></div></template>
<style scoped>.profile-grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:20px}.profile-card{display:flex;align-items:center;gap:20px}.profile-card h2{font-size:26px;margin:7px 0}.actions{display:flex;justify-content:flex-end}@media(max-width:850px){.profile-grid{grid-template-columns:1fr}}</style>
