<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { LayoutDashboard, ShieldCheck, Users, WalletCards, ArrowLeftRight, Trophy, CalendarRange, Award, ScrollText, LogOut, Menu, X, Moon, Sun, Globe2, UserRoundCog, Landmark, Palette, Megaphone } from '@lucide/vue'
import AppLogo from '../components/AppLogo.vue'
import EntityAvatar from '../components/EntityAvatar.vue'
import { authStore } from '../stores/auth'
import { uiStore } from '../stores/ui'
import AppearanceStudio from '../components/AppearanceStudio.vue'
const route=useRoute();const router=useRouter();const mobile=ref(false);const appearanceOpen=ref(false)
const isAdmin=computed(()=>authStore.isAdmin.value)
const nav=computed(()=>[
 {to:'/portal/dashboard',label:'Tổng quan',icon:LayoutDashboard},
 ...(isAdmin.value?[{to:'/portal/clubs',label:'Câu lạc bộ',icon:ShieldCheck}]:[]),
 {to:'/portal/players',label:isAdmin.value?'Cầu thủ':'Đội hình',icon:Users},
 ...(isAdmin.value?[{to:'/portal/world-cup-countries',label:'Quốc gia World Cup',icon:Globe2}]:[]),
 {to:'/portal/finance',label:'Tài chính',icon:WalletCards},
 {to:'/portal/stadiums',label:'Sân vận động',icon:Landmark},
 {to:'/portal/influence',label:'Sức ảnh hưởng',icon:Megaphone},
 {to:'/portal/transfers',label:'Chuyển nhượng',icon:ArrowLeftRight},
 {to:'/portal/competitions',label:'Giải đấu',icon:Trophy},
 ...(isAdmin.value?[{to:'/portal/seasons',label:'Mùa giải',icon:CalendarRange}]:[]),
 {to:'/portal/awards',label:'Danh hiệu & BXH',icon:Award},
 ...(isAdmin.value?[{to:'/portal/activity',label:'Nhật ký',icon:ScrollText}]:[]),
 {to:'/portal/profile',label:'Tài khoản',icon:UserRoundCog},
])
function logout(){authStore.logout();router.push('/login')}
function toggleTheme(){uiStore.setTheme(uiStore.state.theme==='dark'?'light':'dark')}
</script>
<template><div class="portal"><aside :class="{open:mobile}"><div class="side-head"><AppLogo/><button class="btn btn-icon btn-ghost side-close" @click="mobile=false"><X/></button></div><div class="account-mini"><EntityAvatar :src="authStore.user.value?.logoUrl" :name="authStore.user.value?.clubName||authStore.user.value?.username" :size="42"/><div><b>{{ authStore.user.value?.clubName || 'FIFA Admin' }}</b><small>{{ authStore.user.value?.username }}</small></div></div><nav><RouterLink v-for="item in nav" :key="item.to" :to="item.to" @click="mobile=false"><component :is="item.icon" :size="19"/><span>{{ item.label }}</span></RouterLink></nav><div class="side-bottom"><RouterLink to="/" class="btn btn-ghost"><Globe2 :size="17"/>Trang công khai</RouterLink><button class="btn btn-danger" @click="logout"><LogOut :size="17"/>Đăng xuất</button></div></aside><div v-if="mobile" class="overlay" @click="mobile=false"></div><section class="portal-main"><header><button class="btn btn-icon menu-btn" @click="mobile=true"><Menu/></button><div><span class="eyebrow">Football Rank Manager</span><h2>{{ route.meta.title || (isAdmin?'Trung tâm điều hành FIFA':'Khu vực câu lạc bộ') }}</h2></div><div class="header-actions"><button class="btn btn-icon btn-ghost appearance-trigger" title="Tùy biến giao diện" @click="appearanceOpen=true"><Palette :size="19"/></button><button class="btn btn-icon btn-ghost" @click="toggleTheme"><Sun v-if="uiStore.state.theme==='dark'" :size="19"/><Moon v-else :size="19"/></button><EntityAvatar :src="authStore.user.value?.logoUrl" :name="authStore.user.value?.clubName||authStore.user.value?.username" :size="40" round/></div></header><main><RouterView v-slot="{ Component, route: childRoute }"><Transition name="route-motion" mode="out-in"><component :is="Component" :key="childRoute.fullPath"/></Transition></RouterView></main></section><AppearanceStudio :open="appearanceOpen" @close="appearanceOpen=false"/></div></template>
<style scoped>.portal{min-height:100vh;display:grid;grid-template-columns:270px 1fr}.portal aside{position:sticky;top:0;height:100vh;border-right:1px solid var(--line);background:rgba(7,15,27,.88);backdrop-filter:blur(24px);padding:18px 14px;display:flex;flex-direction:column;z-index:1000}:root[data-theme='light'] .portal aside{background:rgba(255,255,255,.9)}.side-head{height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 7px}.side-close{display:none}.account-mini{margin:18px 0 13px;padding:12px;border:1px solid var(--line);border-radius:14px;display:flex;align-items:center;gap:10px;background:rgba(57,130,255,.055)}.account-mini div{min-width:0}.account-mini b,.account-mini small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.account-mini small{color:var(--muted);font-size:11px;margin-top:4px}.portal nav{display:grid;gap:4px;overflow-y:auto;padding:4px}.portal nav a{display:flex;align-items:center;gap:11px;padding:11px 12px;border-radius:11px;color:var(--muted);font-weight:700;font-size:13px;transition:.2s}.portal nav a:hover,.portal nav a.router-link-active{color:var(--text);background:linear-gradient(90deg,rgba(57,130,255,.16),rgba(106,92,255,.08));box-shadow:inset 3px 0 var(--primary)}.side-bottom{margin-top:auto;display:grid;gap:8px;padding:8px}.side-bottom .btn{justify-content:flex-start}.portal-main{min-width:0}.portal-main>header{height:78px;position:sticky;top:0;z-index:700;padding:0 28px;display:flex;align-items:center;gap:16px;border-bottom:1px solid var(--line);background:rgba(6,11,20,.72);backdrop-filter:blur(18px)}:root[data-theme='light'] .portal-main>header{background:rgba(245,248,253,.82)}.portal-main>header h2{font-size:18px;margin-top:3px}.portal-main>main{padding:26px 28px 70px}.header-actions{display:flex;align-items:center;gap:8px;margin-left:auto}.appearance-trigger{position:relative;overflow:hidden}.appearance-trigger:after{content:'';position:absolute;inset:-40%;background:conic-gradient(transparent,var(--primary),var(--cyan),transparent);animation:paletteSpin 4s linear infinite;opacity:.2}.appearance-trigger svg{position:relative;z-index:1}@keyframes paletteSpin{to{transform:rotate(360deg)}}.menu-btn{display:none}.overlay{display:none}@media(max-width:1000px){.portal{grid-template-columns:1fr}.portal aside{position:fixed;left:0;top:0;width:280px;transform:translateX(-110%);transition:.25s}.portal aside.open{transform:none}.side-close,.menu-btn{display:grid}.overlay{display:block;position:fixed;inset:0;z-index:900;background:rgba(0,0,0,.55)}.portal-main>main{padding:20px 16px 60px}.portal-main>header{padding:0 16px}}</style>
