<script setup>
import { computed, ref } from 'vue'
import { Menu, Moon, Sun, LogIn, LayoutDashboard, X, Building2, Palette } from '@lucide/vue'
import AppLogo from '../components/AppLogo.vue'
import { authStore } from '../stores/auth'
import { uiStore } from '../stores/ui'
import AppearanceStudio from '../components/AppearanceStudio.vue'
const mobileOpen=ref(false)
const appearanceOpen=ref(false)
const themeIcon=computed(()=>uiStore.state.theme==='dark'?Sun:Moon)
function toggleTheme(){uiStore.setTheme(uiStore.state.theme==='dark'?'light':'dark')}
</script>
<template><div class="public-layout"><header class="public-header"><div class="container nav"><AppLogo/><nav :class="{open:mobileOpen}"><button class="mobile-close" @click="mobileOpen=false"><X/></button><RouterLink to="/" @click="mobileOpen=false">Trang chủ</RouterLink><RouterLink to="/rankings" @click="mobileOpen=false">Xếp hạng</RouterLink><RouterLink to="/honours" @click="mobileOpen=false">Vinh danh</RouterLink><RouterLink to="/pulse" @click="mobileOpen=false">Nhịp đập</RouterLink><RouterLink to="/influence" @click="mobileOpen=false">Sức ảnh hưởng</RouterLink><RouterLink to="/clubs" @click="mobileOpen=false">Câu lạc bộ</RouterLink><RouterLink to="/stadiums" @click="mobileOpen=false">Sân vận động</RouterLink><RouterLink to="/players" @click="mobileOpen=false">Cầu thủ</RouterLink><RouterLink to="/competitions" @click="mobileOpen=false">Giải đấu</RouterLink></nav><div class="nav-actions"><button class="btn btn-icon btn-ghost appearance-trigger" title="Tùy biến giao diện" @click="appearanceOpen=true"><Palette :size="19"/></button><button class="btn btn-icon btn-ghost" @click="toggleTheme"><component :is="themeIcon" :size="19"/></button><RouterLink v-if="authStore.isAuthenticated.value" class="btn btn-primary hide-mobile" to="/portal/dashboard"><LayoutDashboard :size="17"/>Bảng điều khiển</RouterLink><RouterLink v-else class="btn btn-primary hide-mobile" to="/login"><LogIn :size="17"/>Đăng nhập</RouterLink><button class="btn btn-icon mobile-menu" @click="mobileOpen=true"><Menu/></button></div></div></header><main><RouterView v-slot="{ Component, route: childRoute }"><Transition name="route-motion" mode="out-in"><component :is="Component" :key="childRoute.fullPath"/></Transition></RouterView></main><footer><div class="container footer-grid"><AppLogo/><p>Hệ thống quản lý, xếp hạng CLB, cầu thủ và giải đấu bóng đá theo mùa giải.</p><div class="footer-links"><RouterLink to="/rankings">BXH thế giới</RouterLink><RouterLink to="/honours">Vinh danh</RouterLink><RouterLink to="/pulse">Nhịp đập</RouterLink><RouterLink to="/influence">Sức ảnh hưởng</RouterLink><RouterLink to="/stadiums">Sân vận động</RouterLink><RouterLink to="/competitions">Giải đấu</RouterLink><RouterLink to="/login">Đăng nhập</RouterLink></div></div><div class="container copyright">© 2026 Football Rank Manager. Dữ liệu do FIFA Admin quản lý.</div></footer><AppearanceStudio :open="appearanceOpen" @close="appearanceOpen=false"/></div></template>
<style scoped>.public-header{position:sticky;top:0;z-index:800;background:rgba(6,11,20,.72);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}:root[data-theme='light'] .public-header{background:rgba(245,248,253,.78)}.nav{height:74px;display:flex;align-items:center;justify-content:space-between;gap:24px}.nav nav{display:flex;align-items:center;gap:6px}.nav nav a{padding:10px 13px;border-radius:10px;color:var(--muted);font-weight:700;font-size:14px}.nav nav a:hover,.nav nav a.router-link-active{color:var(--text);background:rgba(57,130,255,.1)}.nav-actions{display:flex;gap:8px}.appearance-trigger{position:relative;overflow:hidden}.appearance-trigger:after{content:'';position:absolute;inset:-45%;background:conic-gradient(transparent,var(--primary),var(--cyan),transparent);animation:paletteSpin 4s linear infinite;opacity:.18}.appearance-trigger svg{position:relative;z-index:1}@keyframes paletteSpin{to{transform:rotate(360deg)}}.mobile-menu,.mobile-close{display:none}footer{border-top:1px solid var(--line);padding:34px 0 20px;background:rgba(5,11,20,.56)}.footer-grid{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:28px}.footer-grid p{max-width:650px}.footer-links{display:flex;gap:16px;color:var(--muted);font-size:13px}.copyright{border-top:1px solid var(--line);margin-top:26px;padding-top:18px;color:var(--muted);font-size:12px}@media(max-width:860px){.nav nav{position:fixed;inset:0 0 0 auto;width:min(330px,88vw);height:100vh;background:var(--panel-solid);padding:80px 18px 20px;display:flex;flex-direction:column;align-items:stretch;transform:translateX(110%);transition:.25s;box-shadow:var(--shadow)}.nav nav.open{transform:none}.nav nav a{font-size:16px;padding:14px}.mobile-menu,.mobile-close{display:grid}.mobile-close{position:absolute;right:16px;top:18px;border:0;background:transparent;color:var(--text)}.footer-grid{grid-template-columns:1fr}.footer-links{flex-wrap:wrap}}</style>
