<script setup>
import { onMounted, ref, watch } from 'vue'
import { Search, Gem, Wallet, Shirt } from '@lucide/vue'
import { api } from '../../services/api';import { money, positionName } from '../../utils'
import PageHeader from '../../components/PageHeader.vue';import LoadingBlock from '../../components/LoadingBlock.vue';import EmptyState from '../../components/EmptyState.vue';import EntityAvatar from '../../components/EntityAvatar.vue';import PaginationBar from '../../components/PaginationBar.vue'
const rows=ref([]),clubs=ref([]),loading=ref(true),meta=ref({page:1,limit:24,total:0}),filters=ref({search:'',position:'',club_id:''});let debounce
async function load(page=1){loading.value=true;try{const r=await api.get('/public/players',{page,limit:24,...filters.value},{auth:false});rows.value=r.data;meta.value=r.meta}finally{loading.value=false}}
watch(filters,()=>{clearTimeout(debounce);debounce=setTimeout(()=>load(1),350)},{deep:true});onMounted(async()=>{const c=await api.get('/public/clubs',{limit:100},{auth:false});clubs.value=c.data;load()})
</script>
<template><div class="container page"><PageHeader eyebrow="Player Database" title="Cầu thủ" description="Thông tin tối giản, rõ ràng: vị trí, số áo, lương, giá trị và câu lạc bộ hiện tại."/><div class="glass card filters"><div class="search"><Search :size="18"/><input v-model="filters.search" class="input" placeholder="Tìm cầu thủ..."/></div><select v-model="filters.position" class="select"><option value="">Tất cả vị trí</option><option value="GK">Thủ môn</option><option value="DF">Hậu vệ</option><option value="MF">Tiền vệ</option><option value="FW">Tiền đạo</option></select><select v-model="filters.club_id" class="select"><option value="">Tất cả CLB</option><option v-for="club in clubs" :key="club.id" :value="club.id">{{ club.name }}</option></select></div><LoadingBlock v-if="loading"/><EmptyState v-else-if="!rows.length"/><div v-else class="grid-4 player-grid"><RouterLink v-for="player in rows" :key="player.id" :to="`/players/${player.id}`" class="glass card card-hover player-card"><div class="player-head"><EntityAvatar :src="player.photo_url" :name="player.full_name" :size="72" round/><span class="shirt"><Shirt :size="15"/>{{ player.shirt_number||'—' }}</span></div><h3>{{ player.full_name }}</h3><p>{{ positionName(player.position) }} · {{ player.club_name||'Cầu thủ tự do' }}</p><div class="player-metrics"><div><Gem :size="15"/><span>Giá trị</span><b>{{ money(player.market_value,true) }}</b></div><div><Wallet :size="15"/><span>Lương/mùa</span><b>{{ money(player.salary_per_season,true) }}</b></div></div></RouterLink></div><PaginationBar v-if="!loading" v-bind="meta" @change="load"/></div></template>
<style scoped>.filters{display:grid;grid-template-columns:1fr 210px 250px;gap:12px;margin-bottom:22px;padding:14px}.search{display:flex;align-items:center;gap:8px}.search .input{border:0;background:transparent;box-shadow:none}.player-card{min-height:285px}.player-head{display:flex;align-items:flex-start;justify-content:space-between}.shirt{display:flex;align-items:center;gap:5px;padding:7px 9px;border-radius:10px;background:rgba(57,130,255,.1);color:#8ab7ff;font-weight:800}.player-card h3{font-size:18px;margin:20px 0 6px}.player-metrics{display:grid;gap:9px;margin-top:22px}.player-metrics div{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:7px;font-size:11px;color:var(--muted)}.player-metrics b{color:var(--text)}@media(max-width:800px){.filters{grid-template-columns:1fr}.player-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.player-grid{grid-template-columns:1fr}}</style>
