<script setup>
import { computed,onMounted,ref } from 'vue'
import { Building2,Users,Crown,Sparkles,MapPin,Ticket,TrendingUp } from '@lucide/vue'
import { api } from '../../services/api'
import { uiStore } from '../../stores/ui'
import { money,number } from '../../utils'
import StadiumArena from '../../components/StadiumArena.vue'
import LoadingBlock from '../../components/LoadingBlock.vue'
import EmptyState from '../../components/EmptyState.vue'
const loading=ref(true),rows=ref([]),search=ref('')
const filtered=computed(()=>{const q=search.value.trim().toLowerCase();return q?rows.value.filter(s=>`${s.name} ${s.city||''} ${s.clubs||''}`.toLowerCase().includes(q)):rows.value})
const totals=computed(()=>({capacity:rows.value.reduce((a,b)=>a+Number(b.capacity_total||0),0),vip:rows.value.reduce((a,b)=>a+Number(b.vip_seats||0),0),world:rows.value.filter(s=>s.stadium_class==='WORLD_CLASS'||s.stadium_class==='ELITE').length}))
onMounted(async()=>{try{rows.value=(await api.get('/public/stadiums')).data||[]}catch(e){uiStore.notify(e.message,'error')}finally{loading.value=false}})
function className(v){return {WORLD_CLASS:'World Class',ELITE:'Elite',A:'Hạng A',B:'Hạng B',C:'Hạng C'}[v]||v}
</script>
<template><div class="page"><div class="container"><section class="showcase-hero"><div><span class="eyebrow"><Sparkles :size="14"/>STADIUM EXPERIENCE</span><h1>Những thánh đường bóng đá</h1><p>Khám phá sức chứa, đẳng cấp cơ sở hạ tầng và năng lực thương mại của các sân vận động trong hệ thống.</p><div class="hero-kpis"><span><Users/>{{ number(totals.capacity,0) }} tổng chỗ</span><span><Crown/>{{ number(totals.vip,0) }} ghế VIP</span><span><TrendingUp/>{{ totals.world }} sân Elite+</span></div></div><StadiumArena v-if="rows[0]" :stadium="rows[0]"/><div v-else class="hero-placeholder"><Building2 :size="52"/></div></section><div class="toolbar glass"><div><h2>Stadium Gallery</h2><p>Dữ liệu được cập nhật từ trung tâm vận hành CLB.</p></div><input v-model="search" class="input" placeholder="Tìm sân, thành phố hoặc CLB..."/></div><LoadingBlock v-if="loading"/><EmptyState v-else-if="!filtered.length" title="Chưa có sân vận động"/><div v-else class="gallery"><article v-for="s in filtered" :key="s.id" class="glass stadium-card card-hover"><StadiumArena :stadium="s" compact/><div class="card-body"><div class="topline"><span class="badge" :class="s.stadium_class==='WORLD_CLASS'?'yellow':'blue'">{{ className(s.stadium_class) }}</span><b>{{ number(s.rating_score,1) }}/100</b></div><h2>{{ s.name }}</h2><p><MapPin :size="13"/>{{ s.city||'Chưa cập nhật' }} · {{ s.clubs||'Sân trung lập' }}</p><div class="stats"><span><Users/>{{ number(s.capacity_total,0) }} chỗ</span><span><Crown/>{{ number(s.vip_seats,0) }} VIP</span><span><Ticket/>Cấp {{ s.level_no }}</span></div></div></article></div><div class="disclaimer glass"><Sparkles/><p>Hệ thống mô phỏng kinh tế sân đấu và tài trợ phục vụ quản trị giải; tên thương hiệu xuất hiện trong dữ liệu mô phỏng không hàm ý quan hệ tài trợ thực tế.</p></div></div></div></template>
<style scoped>.showcase-hero{min-height:390px;display:grid;grid-template-columns:1fr minmax(470px,55%);gap:34px;align-items:center;padding:34px 0}.showcase-hero h1{font-size:clamp(42px,6vw,82px);margin:12px 0;max-width:750px}.showcase-hero p{max-width:650px;font-size:17px}.hero-kpis{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.hero-kpis span{display:flex;align-items:center;gap:7px;padding:10px 12px;border-radius:12px;border:1px solid var(--line);background:rgba(255,255,255,.035);font-weight:750;font-size:12px}.hero-kpis svg{width:15px;color:var(--cyan)}.hero-placeholder{min-height:290px;border:1px dashed var(--line-strong);border-radius:22px;display:grid;place-items:center;color:var(--muted)}.toolbar{padding:18px;margin:8px 0 22px;display:flex;align-items:center;justify-content:space-between;gap:18px}.toolbar h2{margin-bottom:4px}.toolbar .input{max-width:390px}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.stadium-card{padding:8px;overflow:hidden}.card-body{padding:14px 10px 10px}.topline{display:flex;align-items:center;justify-content:space-between}.topline>b{font:800 17px Manrope;color:var(--cyan)}.card-body h2{font-size:24px;margin:12px 0 5px}.card-body p{display:flex;align-items:center;gap:5px;font-size:12px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:15px}.stats span{display:flex;align-items:center;gap:5px;padding:9px;border-radius:10px;background:rgba(255,255,255,.035);font-size:10px;color:var(--muted)}.stats svg{width:13px}.disclaimer{margin-top:24px;padding:16px;display:flex;align-items:center;gap:12px;border-color:rgba(255,200,87,.22)}.disclaimer svg{color:var(--yellow);flex:0 0 auto}.disclaimer p{font-size:12px}@media(max-width:1100px){.showcase-hero{grid-template-columns:1fr}.gallery{grid-template-columns:1fr 1fr}}@media(max-width:700px){.gallery{grid-template-columns:1fr}.toolbar{align-items:stretch;flex-direction:column}.toolbar .input{max-width:none}.showcase-hero{padding-top:20px}.showcase-hero h1{font-size:42px}.stats{grid-template-columns:1fr 1fr}}</style>
