<script setup>
import { onMounted, ref, watch } from 'vue'
import { Search, Shield, Users, Wallet } from '@lucide/vue'
import { api } from '../../services/api';import { money, number } from '../../utils'
import PageHeader from '../../components/PageHeader.vue';import LoadingBlock from '../../components/LoadingBlock.vue';import EmptyState from '../../components/EmptyState.vue';import EntityAvatar from '../../components/EntityAvatar.vue';import RankMovement from '../../components/RankMovement.vue';import PaginationBar from '../../components/PaginationBar.vue'
const loading=ref(true),rows=ref([]),meta=ref({page:1,limit:20,total:0}),search=ref('');let debounce
async function load(page=1){loading.value=true;try{const r=await api.get('/public/clubs',{page,limit:20,search:search.value},{auth:false});rows.value=r.data;meta.value=r.meta}finally{loading.value=false}}
watch(search,()=>{clearTimeout(debounce);debounce=setTimeout(()=>load(1),350)});onMounted(()=>load())
</script>
<template><div class="container page"><PageHeader eyebrow="Club Directory" title="Các câu lạc bộ" description="Khám phá đội hình, tài chính, thành tích và vị thế thế giới của từng câu lạc bộ."/><div class="toolbar glass card search-box"><div class="search-wrap"><Search :size="18"/><input v-model="search" class="input" placeholder="Tìm theo tên, mã hoặc tên viết tắt..."/></div><span class="muted">{{ meta.total }} câu lạc bộ</span></div><LoadingBlock v-if="loading"/><EmptyState v-else-if="!rows.length"/><div v-else class="grid-3 club-grid"><RouterLink v-for="club in rows" :key="club.id" :to="`/clubs/${club.id}`" class="glass card card-hover club-card"><div class="club-top"><EntityAvatar :src="club.logo_url" :name="club.name" :size="68"/><div class="rank-bubble">#{{ club.rank_position||'—' }}</div></div><h3>{{ club.name }}</h3><p>{{ club.code }} · {{ club.short_name }}</p><div class="club-metrics"><div><Users :size="16"/><span>{{ club.player_count }} cầu thủ</span></div><div><Wallet :size="16"/><span>{{ money(club.balance,true) }}</span></div><div><Shield :size="16"/><span>{{ number(club.score) }} điểm</span></div></div><div class="club-footer"><span>Biến động hạng</span><RankMovement :change="club.rank_change" :previous="club.previous_rank"/></div></RouterLink></div><PaginationBar v-if="!loading" v-bind="meta" @change="load"/></div></template>
<style scoped>.search-box{margin-bottom:22px;padding:14px 16px}.search-wrap{display:flex;align-items:center;gap:9px;flex:1;max-width:620px}.search-wrap .input{border:0;background:transparent;box-shadow:none}.club-card{min-height:280px;position:relative}.club-top{display:flex;align-items:flex-start;justify-content:space-between}.rank-bubble{width:50px;height:50px;border-radius:15px;display:grid;place-items:center;font:800 17px Manrope;background:rgba(57,130,255,.1);color:#87b5ff}.club-card h3{font-size:21px;margin:22px 0 6px}.club-metrics{display:grid;gap:9px;margin-top:22px;color:var(--muted);font-size:12px}.club-metrics div{display:flex;align-items:center;gap:8px}.club-footer{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);margin-top:20px;padding-top:15px;font-size:11px;color:var(--muted)}</style>
